-- 합집합
(SELECT 1 UNION SELECT 2 UNION SELECT 3)
UNION
(SELECT 1 UNION SELECT 2 UNION SELECT 5);

(SELECT 1 UNION SELECT 2 UNION SELECT 3)
UNION ALL
(SELECT 1 UNION SELECT 2 UNION SELECT 5);

-- 교집합
(SELECT 1 UNION SELECT 2 UNION SELECT 3)
INTERSECT
(SELECT 1 UNION SELECT 2 UNION SELECT 5);

-- 차집합
(SELECT 1 UNION SELECT 2 UNION SELECT 3)
EXCEPT
(SELECT 1 UNION SELECT 2 UNION SELECT 5);